server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  ai:
    model:
      chat: ollama
    ollama:
      base-url: ${AI_OLLAMA_BASE_URL}
      chat:
        options:
          model: ${AI_OLLAMA_CHAT_MODEL}
          temperature: 0.7
      embedding:
        options:
          model: ${AI_OLLAMA_EMBEDDING_MODEL}
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: ${AI_VECTORSTORE_DIMENSIONS}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expire-time: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}

app:
  ai:
    ocr-model: ${AI_OLLAMA_OCR_MODEL}